version: "3"
services:
  bot:
    build: 
      context: .
      dockerfile: Dockerfile.bot
  server:
    build: 
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "6600:5000"
  redis:
    image: redis:5
